
server:
  port: 9090
  servlet:
    context-path: /sinhvien

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/sinhvien"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true